# Generated by Django 4.2.3 on 2024-02-13 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ByProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название продукта')),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='цена за кг')),
            ],
            options={
                'verbose_name': 'субпродукты',
                'verbose_name_plural': 'субпродукты',
            },
        ),
        migrations.CreateModel(
            name='HalfCarcasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='цена за кг')),
            ],
            options={
                'verbose_name': 'полутуша',
                'verbose_name_plural': 'полутуши',
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='дата')),
                ('half_carcasses_quantity', models.IntegerField(blank=True, null=True, verbose_name='доступное количество в кг')),
                ('by_product_quantity', models.IntegerField(blank=True, null=True, verbose_name='доступное количество субпродуктов в кг')),
                ('by_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.byproduct', verbose_name='субпродукты')),
                ('half_carcasses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.halfcarcasses', verbose_name='полутуши')),
            ],
            options={
                'verbose_name': 'дата',
                'verbose_name_plural': 'даты',
            },
        ),
    ]
