# Generated by Django 4.2.3 on 2024-02-13 21:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('half_carcasses_quantity', models.IntegerField(blank=True, null=True, verbose_name='количество полутуш в кг')),
                ('by_product_quantity', models.IntegerField(blank=True, null=True, verbose_name='количество субпродукты в кг')),
                ('status', models.CharField(choices=[('completed', 'Исполнено'), ('accepted', 'Принят'), ('cancel', 'Отменен')], default='accepted', verbose_name='статус заказа')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='описание')),
                ('date', models.ForeignKey(blank=True, default=django.utils.timezone.now, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.date', verbose_name='дата заказа')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
